### PR TITLE
fix: moudle to module

### PR DESCRIPTION
**Pull request by UniKylin**
1. Fix the comment 'moudle' to 'module' on the index page.
2.Repo name, repository.url、bugs.url 、homepage in package.json have a spelling mistake. '

### CODE REVIEW

**Comment by UniKylin** [comment]
https://github.com/chenshuai2144/merge-cssMoudle-less/issues/8

**Comment by UniKylin** [comment]
@chenshuai2144 Review PR, thanks

**Comment by afc163** [comment]
+1

**Comment by chenshuai2144** [comment]
merge一下

**Pull request closed without merging**
